/*
Project:
Global Semiconductor Supply Chain Intelligence for Consumer Electronics

File:
03_calculate_us_memory_supplier_share.sql

Purpose:
Calculate each supplier country's share of reported U.S. imports
of memory integrated circuits (HS 854232) in 2024.

Important:
This measures supplier share of U.S. import value for HS 854232.
It is not total U.S. semiconductor market share.
*/

USE ROLE SYSADMIN;
USE WAREHOUSE SEMICONDUCTOR_WH;
USE DATABASE SEMICONDUCTOR_SUPPLY_CHAIN_DB;

CREATE OR REPLACE VIEW ANALYTICS.US_MEMORY_SUPPLIER_SHARE_2024 AS

WITH SUPPLIER_IMPORTS AS (
    SELECT
        SUPPLIER_ISO,
        SUPPLIER_COUNTRY,
        SUM(TRADE_VALUE_USD) AS IMPORT_VALUE_USD
    FROM STAGING.US_MEMORY_IMPORTS_2024_CLEAN
    WHERE IS_AGGREGATE = FALSE
      AND SUPPLIER_COUNTRY <> 'World'
    GROUP BY
        SUPPLIER_ISO,
        SUPPLIER_COUNTRY
),

US_TOTAL AS (
    SELECT
        SUM(TRADE_VALUE_USD) AS TOTAL_IMPORT_VALUE_USD
    FROM STAGING.US_MEMORY_IMPORTS_2024_CLEAN
    WHERE IS_AGGREGATE = TRUE
      AND SUPPLIER_COUNTRY = 'World'
)

SELECT
    DENSE_RANK() OVER (
        ORDER BY S.IMPORT_VALUE_USD DESC
    ) AS SUPPLIER_RANK,

    S.SUPPLIER_ISO,
    S.SUPPLIER_COUNTRY,
    S.IMPORT_VALUE_USD,
    T.TOTAL_IMPORT_VALUE_USD,

    ROUND(
        100.0 * S.IMPORT_VALUE_USD
        / NULLIF(T.TOTAL_IMPORT_VALUE_USD, 0),
        2
    ) AS SUPPLIER_SHARE_PCT

FROM SUPPLIER_IMPORTS S
CROSS JOIN US_TOTAL T;

-- Top 10 suppliers
SELECT
    SUPPLIER_RANK,
    SUPPLIER_COUNTRY,
    IMPORT_VALUE_USD,
    SUPPLIER_SHARE_PCT
FROM ANALYTICS.US_MEMORY_SUPPLIER_SHARE_2024
ORDER BY SUPPLIER_RANK
LIMIT 10;

-- Validation: supplier shares should total approximately 100%
SELECT
    ROUND(SUM(SUPPLIER_SHARE_PCT), 2) AS TOTAL_SUPPLIER_SHARE_PCT
FROM ANALYTICS.US_MEMORY_SUPPLIER_SHARE_2024;

-- Validation: partner totals should reconcile with the reported World total
SELECT
    SUM(IMPORT_VALUE_USD) AS SUM_OF_SUPPLIER_IMPORTS,
    MAX(TOTAL_IMPORT_VALUE_USD) AS REPORTED_WORLD_TOTAL,
    SUM(IMPORT_VALUE_USD) - MAX(TOTAL_IMPORT_VALUE_USD) AS DIFFERENCE
FROM ANALYTICS.US_MEMORY_SUPPLIER_SHARE_2024;

-- Executive KPI: top-three supplier concentration
SELECT
    ROUND(SUM(SUPPLIER_SHARE_PCT), 2) AS TOP_3_SUPPLIER_SHARE_PCT
FROM ANALYTICS.US_MEMORY_SUPPLIER_SHARE_2024
WHERE SUPPLIER_RANK <= 3;