/*
Project:
Global Semiconductor Supply Chain Intelligence for Consumer Electronics

File:
02_create_us_memory_staging_view.sql

Purpose:
Create a clean staging view for U.S. monthly imports of memory
integrated circuits (HS 854232) in 2024.

Source:
RAW.COMTRADE_US_MEMORY_IMPORTS_2024_PILOT
*/

USE ROLE SYSADMIN;
USE WAREHOUSE SEMICONDUCTOR_WH;
USE DATABASE SEMICONDUCTOR_SUPPLY_CHAIN_DB;

CREATE OR REPLACE VIEW STAGING.US_MEMORY_IMPORTS_2024_CLEAN AS
SELECT
    TO_DATE(TO_VARCHAR(PERIOD) || '01', 'YYYYMMDD') AS TRADE_MONTH,
    REFYEAR::INTEGER AS TRADE_YEAR,
    REFMONTH::INTEGER AS TRADE_MONTH_NUMBER,

    REPORTERISO::VARCHAR AS REPORTER_ISO,
    REPORTERDESC::VARCHAR AS REPORTER_COUNTRY,

    PARTNERISO::VARCHAR AS SUPPLIER_ISO,
    PARTNERDESC::VARCHAR AS SUPPLIER_COUNTRY,

    TO_VARCHAR(CMDCODE) AS HS_CODE,
    CMDDESC::VARCHAR AS SEMICONDUCTOR_CATEGORY,

    PRIMARYVALUE::NUMBER(38, 0) AS TRADE_VALUE_USD,
    QTY::NUMBER(38, 0) AS QUANTITY,
    NETWGT::NUMBER(38, 3) AS NET_WEIGHT_KG,

    COALESCE(ISREPORTED::BOOLEAN, FALSE) AS IS_REPORTED,
    COALESCE(ISAGGREGATE::BOOLEAN, FALSE) AS IS_AGGREGATE

FROM RAW.COMTRADE_US_MEMORY_IMPORTS_2024_PILOT
WHERE FLOWCODE = 'M'
  AND TO_VARCHAR(CMDCODE) = '854232';

-- Validation preview
SELECT *
FROM STAGING.US_MEMORY_IMPORTS_2024_CLEAN
ORDER BY TRADE_MONTH, SUPPLIER_COUNTRY
LIMIT 20;