USE ROLE SYSADMIN;
USE WAREHOUSE SEMICONDUCTOR_WH;
USE DATABASE SEMICONDUCTOR_SUPPLY_CHAIN_DB;
USE SCHEMA RAW;

-- Confirm the expanded raw table exists

SHOW TABLES LIKE 'COMTRADE_SEMICONDUCTOR_IMPORTS_2023_2024_RAW'
IN SCHEMA RAW;

-- Inspect inferred column names and data types

DESCRIBE TABLE RAW.COMTRADE_SEMICONDUCTOR_IMPORTS_2023_2024_RAW;

-- Validate total rows, periods, products, and partner markets

SELECT
    COUNT(*) AS ROW_COUNT,
    MIN(PERIOD) AS FIRST_PERIOD,
    MAX(PERIOD) AS LAST_PERIOD,
    COUNT(DISTINCT PERIOD) AS PERIOD_COUNT,
    COUNT(DISTINCT TO_VARCHAR(CMDCODE)) AS PRODUCT_COUNT,
    COUNT(DISTINCT PARTNERDESC) AS PARTNER_COUNT
FROM RAW.COMTRADE_SEMICONDUCTOR_IMPORTS_2023_2024_RAW;

-- Confirm coverage for both years and both semiconductor categories

SELECT
    REQUESTEDYEAR,
    TO_VARCHAR(REQUESTEDHSCODE) AS REQUESTED_HS_CODE,
    PRODUCTGROUP,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT PERIOD) AS MONTH_COUNT,
    COUNT(DISTINCT PARTNERDESC) AS PARTNER_COUNT
FROM RAW.COMTRADE_SEMICONDUCTOR_IMPORTS_2023_2024_RAW
GROUP BY
    REQUESTEDYEAR,
    TO_VARCHAR(REQUESTEDHSCODE),
    PRODUCTGROUP
ORDER BY
    REQUESTEDYEAR,
    REQUESTED_HS_CODE;

-- Inspect monthly record counts

SELECT
    PERIOD,
    TO_VARCHAR(CMDCODE) AS HS_CODE,
    PRODUCTGROUP,
    COUNT(*) AS ROW_COUNT
FROM RAW.COMTRADE_SEMICONDUCTOR_IMPORTS_2023_2024_RAW
GROUP BY
    PERIOD,
    TO_VARCHAR(CMDCODE),
    PRODUCTGROUP
ORDER BY
    PERIOD,
    HS_CODE;

-- Confirm one World aggregate row exists per month and product

SELECT
    REQUESTEDYEAR,
    TO_VARCHAR(REQUESTEDHSCODE) AS HS_CODE,
    COUNT(*) AS WORLD_ROW_COUNT,
    COUNT(DISTINCT PERIOD) AS WORLD_MONTH_COUNT,
    SUM(PRIMARYVALUE) AS REPORTED_WORLD_IMPORT_VALUE_USD
FROM RAW.COMTRADE_SEMICONDUCTOR_IMPORTS_2023_2024_RAW
WHERE ISAGGREGATE = TRUE
  AND PARTNERDESC = 'World'
GROUP BY
    REQUESTEDYEAR,
    TO_VARCHAR(REQUESTEDHSCODE)
ORDER BY
    REQUESTEDYEAR,
    HS_CODE;

-- Check for duplicate monthly reporter-partner-product records

WITH DUPLICATE_GROUPS AS (
    SELECT
        PERIOD,
        REPORTERCODE,
        PARTNERCODE,
        FLOWCODE,
        TO_VARCHAR(CMDCODE) AS HS_CODE,
        COUNT(*) AS ROW_COUNT
    FROM RAW.COMTRADE_SEMICONDUCTOR_IMPORTS_2023_2024_RAW
    GROUP BY
        PERIOD,
        REPORTERCODE,
        PARTNERCODE,
        FLOWCODE,
        TO_VARCHAR(CMDCODE)
    HAVING COUNT(*) > 1
)

SELECT
    COUNT(*) AS DUPLICATE_GROUP_COUNT,
    IFF(
        COUNT(*) = 0,
        'PASS: No duplicate trade-grain records found',
        'REVIEW: Duplicate trade-grain records found'
    ) AS VALIDATION_RESULT
FROM DUPLICATE_GROUPS;

-- Inspect sample records from the expanded raw dataset

SELECT
    PERIOD,
    REPORTERDESC,
    PARTNERDESC,
    FLOWDESC,
    TO_VARCHAR(CMDCODE) AS HS_CODE,
    PRODUCTGROUP,
    PRIMARYVALUE,
    ISREPORTED,
    ISAGGREGATE
FROM RAW.COMTRADE_SEMICONDUCTOR_IMPORTS_2023_2024_RAW
ORDER BY
    PERIOD,
    HS_CODE,
    PRIMARYVALUE DESC
LIMIT 30;
