-- Set Snowflake execution context

USE ROLE SYSADMIN;
USE WAREHOUSE SEMICONDUCTOR_WH;
USE DATABASE SEMICONDUCTOR_SUPPLY_CHAIN_DB;


-- Create a clean staging view for expanded semiconductor import data

CREATE OR REPLACE VIEW STAGING.SEMICONDUCTOR_IMPORTS_CLEAN AS

SELECT
    -- Time fields

    TO_DATE(
        TO_VARCHAR(PERIOD) || '01',
        'YYYYMMDD'
    ) AS TRADE_MONTH,

    REFYEAR::INTEGER AS TRADE_YEAR,
    REFMONTH::INTEGER AS TRADE_MONTH_NUMBER,
    TO_VARCHAR(PERIOD) AS TRADE_PERIOD,


    -- Reporter country fields

    TO_VARCHAR(REPORTERCODE) AS REPORTER_UN_CODE,
    REPORTERISO::VARCHAR AS REPORTER_ISO,
    REPORTERDESC::VARCHAR AS REPORTER_COUNTRY,

    COALESCE(
        NULLIF(TRIM(REPORTERISO::VARCHAR), ''),
        REPORTERDESC::VARCHAR
    ) AS REPORTER_KEY,


    -- Partner or supplier market fields

    TO_VARCHAR(PARTNERCODE) AS PARTNER_UN_CODE,
    PARTNERISO::VARCHAR AS PARTNER_ISO,
    PARTNERDESC::VARCHAR AS SUPPLIER_COUNTRY,

    COALESCE(
        NULLIF(TRIM(PARTNERISO::VARCHAR), ''),
        PARTNERDESC::VARCHAR
    ) AS PARTNER_KEY,


    -- Trade-flow fields

    FLOWCODE::VARCHAR AS FLOW_CODE,
    FLOWDESC::VARCHAR AS FLOW_DESCRIPTION,


    -- Product fields

    TO_VARCHAR(CMDCODE) AS HS_CODE,
    CMDDESC::VARCHAR AS HS_DESCRIPTION,
    PRODUCTGROUP::VARCHAR AS PRODUCT_GROUP,

    CLASSIFICATIONCODE::VARCHAR AS CLASSIFICATION_CODE,
    CLASSIFICATIONSEARCHCODE::VARCHAR
        AS CLASSIFICATION_SEARCH_CODE,


    -- Measures

    PRIMARYVALUE::NUMBER(38, 2) AS TRADE_VALUE_USD,
    QTY::NUMBER(38, 3) AS QUANTITY,
    NETWGT::NUMBER(38, 3) AS NET_WEIGHT_KG,
    GROSSWGT::NUMBER(38, 3) AS GROSS_WEIGHT_KG,

    CIFVALUE::NUMBER(38, 2) AS CIF_VALUE_USD,
    FOBVALUE::NUMBER(38, 2) AS FOB_VALUE_USD,


    -- Data-quality flags

    COALESCE(ISREPORTED::BOOLEAN, FALSE) AS IS_REPORTED,
    COALESCE(ISAGGREGATE::BOOLEAN, FALSE) AS IS_AGGREGATE,
    COALESCE(ISQTYESTIMATED::BOOLEAN, FALSE)
        AS IS_QUANTITY_ESTIMATED,
    COALESCE(ISNETWGTESTIMATED::BOOLEAN, FALSE)
        AS IS_NET_WEIGHT_ESTIMATED,


    -- Extraction metadata

    REQUESTEDYEAR::INTEGER AS REQUESTED_YEAR,
    TO_VARCHAR(REQUESTEDHSCODE) AS REQUESTED_HS_CODE,
    REQUESTEDPERIOD::VARCHAR AS REQUESTED_PERIOD,
    EXTRACTIONMETHOD::VARCHAR AS EXTRACTION_METHOD,
    EXTRACTEDATUTC::TIMESTAMP_TZ AS EXTRACTED_AT_UTC,

    'COMTRADE_SEMICONDUCTOR_IMPORTS_2023_2024_RAW'
        AS SOURCE_TABLE

FROM RAW.COMTRADE_SEMICONDUCTOR_IMPORTS_2023_2024_RAW

WHERE TYPECODE = 'C'
  AND FREQCODE = 'M'
  AND FLOWCODE = 'M'
  AND TO_VARCHAR(CMDCODE) IN (
      '854231',
      '854232'
  );

-- Check staging-view coverage

SELECT
    COUNT(*) AS ROW_COUNT,
    MIN(TRADE_MONTH) AS FIRST_MONTH,
    MAX(TRADE_MONTH) AS LAST_MONTH,
    COUNT(DISTINCT TRADE_MONTH) AS MONTH_COUNT,
    COUNT(DISTINCT HS_CODE) AS PRODUCT_COUNT,
    COUNT(DISTINCT PARTNER_KEY) AS PARTNER_COUNT

FROM STAGING.SEMICONDUCTOR_IMPORTS_CLEAN;

-- Confirm complete monthly coverage by year and product

SELECT
    TRADE_YEAR,
    HS_CODE,
    PRODUCT_GROUP,
    COUNT(*) AS ROW_COUNT,
    COUNT(DISTINCT TRADE_MONTH) AS MONTH_COUNT,
    COUNT(DISTINCT PARTNER_KEY) AS PARTNER_COUNT

FROM STAGING.SEMICONDUCTOR_IMPORTS_CLEAN

GROUP BY
    TRADE_YEAR,
    HS_CODE,
    PRODUCT_GROUP

ORDER BY
    TRADE_YEAR,
    HS_CODE;

-- Check for missing analytical keys and values

SELECT
    COUNT_IF(TRADE_MONTH IS NULL) AS MISSING_TRADE_MONTH,
    COUNT_IF(REPORTER_KEY IS NULL) AS MISSING_REPORTER,
    COUNT_IF(PARTNER_KEY IS NULL) AS MISSING_PARTNER,
    COUNT_IF(HS_CODE IS NULL) AS MISSING_HS_CODE,
    COUNT_IF(TRADE_VALUE_USD IS NULL) AS MISSING_TRADE_VALUE

FROM STAGING.SEMICONDUCTOR_IMPORTS_CLEAN;

-- Check uniqueness at the intended monthly trade grain

WITH DUPLICATE_GROUPS AS (
    SELECT
        TRADE_MONTH,
        REPORTER_KEY,
        PARTNER_KEY,
        FLOW_CODE,
        HS_CODE,
        COUNT(*) AS ROW_COUNT

    FROM STAGING.SEMICONDUCTOR_IMPORTS_CLEAN

    GROUP BY
        TRADE_MONTH,
        REPORTER_KEY,
        PARTNER_KEY,
        FLOW_CODE,
        HS_CODE

    HAVING COUNT(*) > 1
)

SELECT
    COUNT(*) AS DUPLICATE_GROUP_COUNT,

    IFF(
        COUNT(*) = 0,
        'PASS: No duplicate staging records found',
        'REVIEW: Duplicate staging records found'
    ) AS VALIDATION_RESULT

FROM DUPLICATE_GROUPS;

-- Inspect sample cleaned records

SELECT
    TRADE_MONTH,
    REPORTER_COUNTRY,
    SUPPLIER_COUNTRY,
    FLOW_DESCRIPTION,
    HS_CODE,
    PRODUCT_GROUP,
    TRADE_VALUE_USD,
    IS_REPORTED,
    IS_AGGREGATE

FROM STAGING.SEMICONDUCTOR_IMPORTS_CLEAN

ORDER BY
    TRADE_MONTH,
    HS_CODE,
    TRADE_VALUE_USD DESC

LIMIT 30;