-- Set Snowflake execution context

USE ROLE SYSADMIN;
USE WAREHOUSE SEMICONDUCTOR_WH;
USE DATABASE SEMICONDUCTOR_SUPPLY_CHAIN_DB;


-- Merge reporter countries, supplier markets, and aggregate markets

MERGE INTO ANALYTICS.DIM_COUNTRY AS TARGET

USING (
    SELECT
        COUNTRY_CODE,
        ISO_ALPHA_3,
        COUNTRY_NAME,
        SOURCE_COUNTRY_NAME,
        REGION,
        SUBREGION,
        IS_AGGREGATE_MARKET

    FROM (
        -- Reporter countries

        SELECT DISTINCT
            REPORTER_KEY AS COUNTRY_CODE,
            REPORTER_ISO AS ISO_ALPHA_3,
            REPORTER_COUNTRY AS COUNTRY_NAME,
            REPORTER_COUNTRY AS SOURCE_COUNTRY_NAME,
            CAST(NULL AS VARCHAR) AS REGION,
            CAST(NULL AS VARCHAR) AS SUBREGION,
            FALSE AS IS_AGGREGATE_MARKET

        FROM STAGING.SEMICONDUCTOR_IMPORTS_CLEAN

        UNION ALL

        -- Supplier and aggregate partner markets

        SELECT DISTINCT
            PARTNER_KEY AS COUNTRY_CODE,
            PARTNER_ISO AS ISO_ALPHA_3,
            SUPPLIER_COUNTRY AS COUNTRY_NAME,
            SUPPLIER_COUNTRY AS SOURCE_COUNTRY_NAME,
            CAST(NULL AS VARCHAR) AS REGION,
            CAST(NULL AS VARCHAR) AS SUBREGION,
            IS_AGGREGATE AS IS_AGGREGATE_MARKET

        FROM STAGING.SEMICONDUCTOR_IMPORTS_CLEAN
    )

    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY COUNTRY_CODE
        ORDER BY
            IS_AGGREGATE_MARKET,
            COUNTRY_NAME
    ) = 1
) AS SOURCE

ON TARGET.COUNTRY_CODE = SOURCE.COUNTRY_CODE

WHEN MATCHED THEN
    UPDATE SET
        TARGET.ISO_ALPHA_3 = SOURCE.ISO_ALPHA_3,
        TARGET.COUNTRY_NAME = SOURCE.COUNTRY_NAME,
        TARGET.SOURCE_COUNTRY_NAME = SOURCE.SOURCE_COUNTRY_NAME,
        TARGET.IS_AGGREGATE_MARKET = SOURCE.IS_AGGREGATE_MARKET

WHEN NOT MATCHED THEN
    INSERT (
        COUNTRY_CODE,
        ISO_ALPHA_3,
        COUNTRY_NAME,
        SOURCE_COUNTRY_NAME,
        REGION,
        SUBREGION,
        IS_AGGREGATE_MARKET
    )
    VALUES (
        SOURCE.COUNTRY_CODE,
        SOURCE.ISO_ALPHA_3,
        SOURCE.COUNTRY_NAME,
        SOURCE.SOURCE_COUNTRY_NAME,
        SOURCE.REGION,
        SOURCE.SUBREGION,
        SOURCE.IS_AGGREGATE_MARKET
    );


-- Merge semiconductor product categories

MERGE INTO ANALYTICS.DIM_PRODUCT AS TARGET

USING (
    SELECT
        HS_CODE,
        HS_DESCRIPTION,
        PRODUCT_GROUP,

        CASE
            WHEN HS_CODE = '854231'
                THEN 'Relevant to computing, displays, smart devices and embedded electronics'

            WHEN HS_CODE = '854232'
                THEN 'Relevant to computers, displays, smartphones and connected devices'

            ELSE
                'Relevant to consumer-electronics semiconductor supply chains'
        END AS CONSUMER_ELECTRONICS_RELEVANCE,

        CLASSIFICATION_CODE AS CLASSIFICATION_VERSION,
        TRUE AS IS_IN_MVP_SCOPE

    FROM STAGING.SEMICONDUCTOR_IMPORTS_CLEAN

    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY HS_CODE
        ORDER BY HS_DESCRIPTION
    ) = 1
) AS SOURCE

ON TARGET.HS_CODE = SOURCE.HS_CODE

WHEN MATCHED THEN
    UPDATE SET
        TARGET.HS_DESCRIPTION = SOURCE.HS_DESCRIPTION,
        TARGET.PRODUCT_GROUP = SOURCE.PRODUCT_GROUP,
        TARGET.CONSUMER_ELECTRONICS_RELEVANCE =
            SOURCE.CONSUMER_ELECTRONICS_RELEVANCE,
        TARGET.CLASSIFICATION_VERSION =
            SOURCE.CLASSIFICATION_VERSION,
        TARGET.IS_IN_MVP_SCOPE =
            SOURCE.IS_IN_MVP_SCOPE

WHEN NOT MATCHED THEN
    INSERT (
        HS_CODE,
        HS_DESCRIPTION,
        PRODUCT_GROUP,
        CONSUMER_ELECTRONICS_RELEVANCE,
        CLASSIFICATION_VERSION,
        IS_IN_MVP_SCOPE
    )
    VALUES (
        SOURCE.HS_CODE,
        SOURCE.HS_DESCRIPTION,
        SOURCE.PRODUCT_GROUP,
        SOURCE.CONSUMER_ELECTRONICS_RELEVANCE,
        SOURCE.CLASSIFICATION_VERSION,
        SOURCE.IS_IN_MVP_SCOPE
    );


-- Merge all months from January 2023 through December 2024

MERGE INTO ANALYTICS.DIM_DATE AS TARGET

USING (
    WITH DISTINCT_MONTHS AS (
        SELECT DISTINCT
            TRADE_MONTH

        FROM STAGING.SEMICONDUCTOR_IMPORTS_CLEAN
    )

    SELECT
        TRADE_MONTH,
        YEAR(TRADE_MONTH) AS YEAR,
        MONTH(TRADE_MONTH) AS MONTH_NUMBER,
        TO_CHAR(TRADE_MONTH, 'MMMM') AS MONTH_NAME,
        'Q' || QUARTER(TRADE_MONTH) AS QUARTER,
        TO_CHAR(TRADE_MONTH, 'YYYY-MM') AS YEAR_MONTH,

        COUNT(*) OVER (
            PARTITION BY YEAR(TRADE_MONTH)
        ) = 12 AS IS_COMPLETE_YEAR

    FROM DISTINCT_MONTHS
) AS SOURCE

ON TARGET.TRADE_MONTH = SOURCE.TRADE_MONTH

WHEN MATCHED THEN
    UPDATE SET
        TARGET.YEAR = SOURCE.YEAR,
        TARGET.MONTH_NUMBER = SOURCE.MONTH_NUMBER,
        TARGET.MONTH_NAME = SOURCE.MONTH_NAME,
        TARGET.QUARTER = SOURCE.QUARTER,
        TARGET.YEAR_MONTH = SOURCE.YEAR_MONTH,
        TARGET.IS_COMPLETE_YEAR = SOURCE.IS_COMPLETE_YEAR

WHEN NOT MATCHED THEN
    INSERT (
        TRADE_MONTH,
        YEAR,
        MONTH_NUMBER,
        MONTH_NAME,
        QUARTER,
        YEAR_MONTH,
        IS_COMPLETE_YEAR
    )
    VALUES (
        SOURCE.TRADE_MONTH,
        SOURCE.YEAR,
        SOURCE.MONTH_NUMBER,
        SOURCE.MONTH_NAME,
        SOURCE.QUARTER,
        SOURCE.YEAR_MONTH,
        SOURCE.IS_COMPLETE_YEAR
    );


-- Merge the expanded monthly trade records into the fact table

MERGE INTO ANALYTICS.FACT_SEMICONDUCTOR_TRADE AS TARGET

USING (
    SELECT
        TRADE_MONTH,
        REPORTER_KEY AS REPORTER_CODE,
        PARTNER_KEY AS PARTNER_CODE,
        FLOW_CODE,
        HS_CODE,

        SUM(TRADE_VALUE_USD) AS TRADE_VALUE_USD,
        SUM(QUANTITY) AS QUANTITY,
        SUM(NET_WEIGHT_KG) AS NET_WEIGHT_KG,

        MAX(
            IFF(IS_AGGREGATE, 1, 0)
        ) = 1 AS IS_AGGREGATE,

        MAX(
            IFF(IS_REPORTED, 1, 0)
        ) = 1 AS IS_REPORTED,

        MAX(CLASSIFICATION_CODE) AS CLASSIFICATION_CODE,

        'us_semiconductor_imports_monthly_2023_2024_preview.csv'
            AS SOURCE_FILE

    FROM STAGING.SEMICONDUCTOR_IMPORTS_CLEAN

    GROUP BY
        TRADE_MONTH,
        REPORTER_KEY,
        PARTNER_KEY,
        FLOW_CODE,
        HS_CODE
) AS SOURCE

ON  TARGET.TRADE_MONTH = SOURCE.TRADE_MONTH
AND TARGET.REPORTER_CODE = SOURCE.REPORTER_CODE
AND TARGET.PARTNER_CODE = SOURCE.PARTNER_CODE
AND TARGET.FLOW_CODE = SOURCE.FLOW_CODE
AND TARGET.HS_CODE = SOURCE.HS_CODE

WHEN MATCHED THEN
    UPDATE SET
        TARGET.TRADE_VALUE_USD = SOURCE.TRADE_VALUE_USD,
        TARGET.QUANTITY = SOURCE.QUANTITY,
        TARGET.NET_WEIGHT_KG = SOURCE.NET_WEIGHT_KG,
        TARGET.IS_AGGREGATE = SOURCE.IS_AGGREGATE,
        TARGET.IS_REPORTED = SOURCE.IS_REPORTED,
        TARGET.CLASSIFICATION_CODE = SOURCE.CLASSIFICATION_CODE,
        TARGET.SOURCE_FILE = SOURCE.SOURCE_FILE

WHEN NOT MATCHED THEN
    INSERT (
        TRADE_MONTH,
        REPORTER_CODE,
        PARTNER_CODE,
        FLOW_CODE,
        HS_CODE,
        TRADE_VALUE_USD,
        QUANTITY,
        NET_WEIGHT_KG,
        IS_AGGREGATE,
        IS_REPORTED,
        CLASSIFICATION_CODE,
        SOURCE_FILE
    )
    VALUES (
        SOURCE.TRADE_MONTH,
        SOURCE.REPORTER_CODE,
        SOURCE.PARTNER_CODE,
        SOURCE.FLOW_CODE,
        SOURCE.HS_CODE,
        SOURCE.TRADE_VALUE_USD,
        SOURCE.QUANTITY,
        SOURCE.NET_WEIGHT_KG,
        SOURCE.IS_AGGREGATE,
        SOURCE.IS_REPORTED,
        SOURCE.CLASSIFICATION_CODE,
        SOURCE.SOURCE_FILE
    );


-- Validate country dimension

SELECT
    COUNT(*) AS COUNTRY_ROW_COUNT,
    COUNT_IF(IS_AGGREGATE_MARKET = TRUE)
        AS AGGREGATE_MARKET_COUNT

FROM ANALYTICS.DIM_COUNTRY;


-- Validate product dimension

SELECT
    HS_CODE,
    HS_DESCRIPTION,
    PRODUCT_GROUP,
    CLASSIFICATION_VERSION,
    IS_IN_MVP_SCOPE

FROM ANALYTICS.DIM_PRODUCT

ORDER BY HS_CODE;


-- Expected:
-- 854231 - Processors and controllers
-- 854232 - Memory integrated circuits


-- Validate date coverage

SELECT
    MIN(TRADE_MONTH) AS FIRST_MONTH,
    MAX(TRADE_MONTH) AS LAST_MONTH,
    COUNT(*) AS DATE_ROW_COUNT,
    COUNT(DISTINCT YEAR) AS YEAR_COUNT,
    COUNT_IF(IS_COMPLETE_YEAR = TRUE)
        AS COMPLETE_MONTH_ROW_COUNT

FROM ANALYTICS.DIM_DATE;


-- Expected:
-- FIRST_MONTH: 2023-01-01
-- LAST_MONTH: 2024-12-01
-- DATE_ROW_COUNT: 24
-- YEAR_COUNT: 2
-- COMPLETE_MONTH_ROW_COUNT: 24


-- Validate overall fact-table coverage

SELECT
    COUNT(*) AS FACT_ROW_COUNT,
    MIN(TRADE_MONTH) AS FIRST_MONTH,
    MAX(TRADE_MONTH) AS LAST_MONTH,
    COUNT(DISTINCT TRADE_MONTH) AS MONTH_COUNT,
    COUNT(DISTINCT HS_CODE) AS PRODUCT_COUNT,
    COUNT(DISTINCT PARTNER_CODE) AS PARTNER_COUNT

FROM ANALYTICS.FACT_SEMICONDUCTOR_TRADE;


-- Expected:
-- FIRST_MONTH: 2023-01-01
-- LAST_MONTH: 2024-12-01
-- MONTH_COUNT: 24
-- PRODUCT_COUNT: 2


-- Confirm monthly coverage for each year and product

SELECT
    D.YEAR,
    F.HS_CODE,
    P.PRODUCT_GROUP,
    COUNT(*) AS FACT_ROW_COUNT,
    COUNT(DISTINCT F.TRADE_MONTH) AS MONTH_COUNT,
    COUNT(DISTINCT F.PARTNER_CODE) AS PARTNER_COUNT

FROM ANALYTICS.FACT_SEMICONDUCTOR_TRADE AS F

LEFT JOIN ANALYTICS.DIM_DATE AS D
    ON F.TRADE_MONTH = D.TRADE_MONTH

LEFT JOIN ANALYTICS.DIM_PRODUCT AS P
    ON F.HS_CODE = P.HS_CODE

GROUP BY
    D.YEAR,
    F.HS_CODE,
    P.PRODUCT_GROUP

ORDER BY
    D.YEAR,
    F.HS_CODE;


-- Expected four rows:
-- 2023 | 854231 | 12 months
-- 2023 | 854232 | 12 months
-- 2024 | 854231 | 12 months
-- 2024 | 854232 | 12 months


-- Check for fact records that do not match dimensions

SELECT
    COUNT_IF(REPORTER.COUNTRY_CODE IS NULL)
        AS MISSING_REPORTERS,

    COUNT_IF(SUPPLIER.COUNTRY_CODE IS NULL)
        AS MISSING_SUPPLIERS,

    COUNT_IF(P.HS_CODE IS NULL)
        AS MISSING_PRODUCTS,

    COUNT_IF(D.TRADE_MONTH IS NULL)
        AS MISSING_DATES

FROM ANALYTICS.FACT_SEMICONDUCTOR_TRADE AS F

LEFT JOIN ANALYTICS.DIM_COUNTRY AS REPORTER
    ON F.REPORTER_CODE = REPORTER.COUNTRY_CODE

LEFT JOIN ANALYTICS.DIM_COUNTRY AS SUPPLIER
    ON F.PARTNER_CODE = SUPPLIER.COUNTRY_CODE

LEFT JOIN ANALYTICS.DIM_PRODUCT AS P
    ON F.HS_CODE = P.HS_CODE

LEFT JOIN ANALYTICS.DIM_DATE AS D
    ON F.TRADE_MONTH = D.TRADE_MONTH;


-- Expected:
-- All four values should be 0


-- Check for duplicate fact-table grain combinations

WITH DUPLICATE_GROUPS AS (
    SELECT
        TRADE_MONTH,
        REPORTER_CODE,
        PARTNER_CODE,
        FLOW_CODE,
        HS_CODE,
        COUNT(*) AS ROW_COUNT

    FROM ANALYTICS.FACT_SEMICONDUCTOR_TRADE

    GROUP BY
        TRADE_MONTH,
        REPORTER_CODE,
        PARTNER_CODE,
        FLOW_CODE,
        HS_CODE

    HAVING COUNT(*) > 1
)

SELECT
    COUNT(*) AS DUPLICATE_GROUP_COUNT,

    IFF(
        COUNT(*) = 0,
        'PASS: No duplicate fact-table grain detected',
        'FAIL: Duplicate fact-table grain detected'
    ) AS VALIDATION_RESULT

FROM DUPLICATE_GROUPS;


-- Expected:
-- DUPLICATE_GROUP_COUNT: 0
-- VALIDATION_RESULT: PASS


-- Show annual reported World totals by product

SELECT
    D.YEAR,
    F.HS_CODE,
    P.PRODUCT_GROUP,

    SUM(F.TRADE_VALUE_USD)
        AS REPORTED_WORLD_IMPORT_VALUE_USD,

    COUNT(DISTINCT F.TRADE_MONTH)
        AS MONTH_COUNT

FROM ANALYTICS.FACT_SEMICONDUCTOR_TRADE AS F

LEFT JOIN ANALYTICS.DIM_DATE AS D
    ON F.TRADE_MONTH = D.TRADE_MONTH

LEFT JOIN ANALYTICS.DIM_PRODUCT AS P
    ON F.HS_CODE = P.HS_CODE

WHERE F.IS_AGGREGATE = TRUE
  AND F.PARTNER_CODE = 'World'

GROUP BY
    D.YEAR,
    F.HS_CODE,
    P.PRODUCT_GROUP

ORDER BY
    D.YEAR,
    F.HS_CODE;


-- Expected:
-- Four rows, each with MONTH_COUNT = 12


-- Inspect readable records from the completed star schema

SELECT
    F.TRADE_MONTH,
    D.YEAR,
    D.MONTH_NAME,
    D.QUARTER,

    REPORTER.COUNTRY_NAME AS REPORTER_COUNTRY,
    SUPPLIER.COUNTRY_NAME AS SUPPLIER_MARKET,

    F.HS_CODE,
    P.PRODUCT_GROUP,
    F.TRADE_VALUE_USD,
    F.IS_REPORTED,
    F.IS_AGGREGATE

FROM ANALYTICS.FACT_SEMICONDUCTOR_TRADE AS F

LEFT JOIN ANALYTICS.DIM_DATE AS D
    ON F.TRADE_MONTH = D.TRADE_MONTH

LEFT JOIN ANALYTICS.DIM_COUNTRY AS REPORTER
    ON F.REPORTER_CODE = REPORTER.COUNTRY_CODE

LEFT JOIN ANALYTICS.DIM_COUNTRY AS SUPPLIER
    ON F.PARTNER_CODE = SUPPLIER.COUNTRY_CODE

LEFT JOIN ANALYTICS.DIM_PRODUCT AS P
    ON F.HS_CODE = P.HS_CODE

ORDER BY
    F.TRADE_MONTH,
    F.HS_CODE,
    F.TRADE_VALUE_USD DESC

LIMIT 30;