USE ROLE SYSADMIN;
USE WAREHOUSE SEMICONDUCTOR_WH;
USE DATABASE SEMICONDUCTOR_SUPPLY_CHAIN_DB;
USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS DIM_COUNTRY (
    COUNTRY_CODE VARCHAR,
    ISO_ALPHA_3 VARCHAR,
    COUNTRY_NAME VARCHAR,
    SOURCE_COUNTRY_NAME VARCHAR,
    REGION VARCHAR,
    SUBREGION VARCHAR,
    IS_AGGREGATE_MARKET BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIM_PRODUCT (
    HS_CODE VARCHAR,
    HS_DESCRIPTION VARCHAR,
    PRODUCT_GROUP VARCHAR,
    CONSUMER_ELECTRONICS_RELEVANCE VARCHAR,
    CLASSIFICATION_VERSION VARCHAR,
    IS_IN_MVP_SCOPE BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIM_DATE (
    TRADE_MONTH DATE,
    YEAR INTEGER,
    MONTH_NUMBER INTEGER,
    MONTH_NAME VARCHAR,
    QUARTER VARCHAR,
    YEAR_MONTH VARCHAR,
    IS_COMPLETE_YEAR BOOLEAN
);

CREATE TABLE IF NOT EXISTS FACT_SEMICONDUCTOR_TRADE (
    TRADE_MONTH DATE,
    REPORTER_CODE VARCHAR,
    PARTNER_CODE VARCHAR,
    FLOW_CODE VARCHAR,
    HS_CODE VARCHAR,
    TRADE_VALUE_USD NUMBER(38, 0),
    QUANTITY NUMBER(38, 0),
    NET_WEIGHT_KG NUMBER(38, 3),
    IS_AGGREGATE BOOLEAN,
    IS_REPORTED BOOLEAN,
    CLASSIFICATION_CODE VARCHAR,
    SOURCE_FILE VARCHAR
);

SHOW TABLES IN SCHEMA ANALYTICS;
